"""Generate contract artifacts for consolidated week data.

This script generates:
1. JSON Schema (week-data.schema.json)
2. C# DTO classes (WeekDataDto.cs)
"""

from __future__ import annotations

import argparse
import json
import sys
from types import UnionType
from pathlib import Path
from typing import Any, get_args, get_origin

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src" / "intervals_icu"))

import week_data_schema as week_schema

from week_data_schema import WeekData


def _snake_to_pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def _is_optional(annotation: Any) -> tuple[bool, list[Any]]:
    origin = get_origin(annotation)
    if origin in (UnionType, getattr(__import__("typing"), "Union", UnionType)):
        args = [a for a in get_args(annotation)]
        non_none = [a for a in args if a is not type(None)]
        return len(non_none) != len(args), non_none
    return False, [annotation]


def _is_schema_model(tp: Any) -> bool:
    return isinstance(tp, type) and issubclass(tp, week_schema._SchemaModel)


def _map_type(annotation: Any) -> tuple[str, bool]:
    optional, members = _is_optional(annotation)
    if not members:
        return "JsonElement", True

    # Prefer schema model when union includes model + loose dict/any fallback.
    model_member = next((m for m in members if _is_schema_model(m)), None)
    if model_member is not None:
        return f"{model_member.__name__}Dto", optional

    # Prefer scalar over Any in unions.
    scalar_member = next((m for m in members if m in (str, int, float, bool)), None)
    if scalar_member is not None:
        members = [scalar_member]

    member = members[0]
    origin = get_origin(member)

    if _is_schema_model(member):
        return f"{member.__name__}Dto", optional

    if member is str:
        return "string", optional
    if member is int:
        return "int", optional
    if member is float:
        return "double", optional
    if member is bool:
        return "bool", optional
    if member is Any:
        return "JsonElement", True

    if origin in (list,):
        item_type, item_optional = _map_type(get_args(member)[0])
        if item_optional and item_type in {"int", "double", "bool", "JsonElement"}:
            item_type = f"{item_type}?"
        elif item_optional and not item_type.endswith("?"):
            item_type = f"{item_type}?"
        return f"List<{item_type}>", optional

    if origin in (dict,):
        key_t, value_t = get_args(member)
        if key_t is str:
            mapped_value, mapped_optional = _map_type(value_t)
            if mapped_optional and mapped_value in {"int", "double", "bool", "JsonElement"}:
                mapped_value = f"{mapped_value}?"
            elif mapped_optional and not mapped_value.endswith("?"):
                mapped_value = f"{mapped_value}?"
            return f"Dictionary<string, {mapped_value}>", optional

    return "JsonElement", True


def _is_value_type(csharp_type: str) -> bool:
    return csharp_type in {"int", "double", "bool", "JsonElement"}


def _render_csharp_dtos() -> str:
    lines: list[str] = []
    lines.append("// <auto-generated />")
    lines.append("using System.Collections.Generic;")
    lines.append("using System.Text.Json;")
    lines.append("using System.Text.Json.Serialization;")
    lines.append("")
    lines.append("namespace IntervalsIcuSync.Contracts;")
    lines.append("")

    model_types: list[type] = [
        obj
        for obj in week_schema.__dict__.values()
        if isinstance(obj, type)
        and issubclass(obj, week_schema._SchemaModel)
        and obj is not week_schema._SchemaModel
    ]
    model_types.sort(key=lambda m: (0 if m.__name__ == "WeekData" else 1, m.__name__))

    for model_type in model_types:
        lines.append(f"public class {model_type.__name__}Dto")
        lines.append("{")
        for json_name, field in model_type.model_fields.items():
            mapped_type, nullable = _map_type(field.annotation)
            prop_name = _snake_to_pascal(json_name)

            final_type = mapped_type
            if nullable and _is_value_type(mapped_type):
                final_type = f"{mapped_type}?"
            elif nullable and not mapped_type.endswith("?"):
                final_type = f"{mapped_type}?"

            lines.append(f"    [JsonPropertyName(\"{json_name}\")]")
            lines.append(f"    public {final_type} {prop_name} {{ get; set; }}")
            lines.append("")

        lines.append("    [JsonExtensionData]")
        lines.append("    public Dictionary<string, JsonElement>? Extra { get; set; }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate week-data contract artifacts from the Pydantic WeekData model."
    )
    parser.add_argument(
        "--schema-output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "contracts" / "week-data" / "week-data.schema.json",
        help="JSON Schema output path (default: contracts/week-data/week-data.schema.json)",
    )
    parser.add_argument(
        "--dto-output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "contracts" / "week-data" / "WeekDataDto.cs",
        help="C# DTO output path (default: contracts/week-data/WeekDataDto.cs)",
    )
    args = parser.parse_args()

    args.schema_output.parent.mkdir(parents=True, exist_ok=True)
    args.dto_output.parent.mkdir(parents=True, exist_ok=True)

    schema = WeekData.model_json_schema()
    args.schema_output.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    dto_code = _render_csharp_dtos()
    args.dto_output.write_text(dto_code + "\n", encoding="utf-8")

    print(f"Schema written to: {args.schema_output}")
    print(f"C# DTO written to: {args.dto_output}")


if __name__ == "__main__":
    main()
