<#
.SYNOPSIS
    Sets up GitHub Secrets and Bicep parameters from config.ps1.

.DESCRIPTION
    Reads config.ps1 (not committed) and applies values to:
      -GitHub   GitHub repository secrets via gh CLI
      -Bicep    Generates infra/main.local.bicepparam for local deployments
      -All      Both targets

.EXAMPLE
    .\setup.ps1 -All
    .\setup.ps1 -GitHub      # GitHub Secrets only
    .\setup.ps1 -Bicep       # Generate bicepparam only

.NOTES
    Requires: GitHub CLI (gh) for -GitHub flag.
    Install:  winget install GitHub.cli
#>
param(
    [switch]$GitHub,
    [switch]$Bicep,
    [switch]$All
)

#---------------------------------------------------------------------------
# Load config
#---------------------------------------------------------------------------
$configPath = Join-Path $PSScriptRoot "config.ps1"
if (-not (Test-Path $configPath)) {
    Write-Host "config.ps1 not found." -ForegroundColor Red
    Write-Host "Copy config.example.ps1 to config.ps1 and fill in your values." -ForegroundColor Yellow
    exit 1
}
. $configPath

#---------------------------------------------------------------------------
# 1. GitHub Secrets via gh CLI
#---------------------------------------------------------------------------
if ($GitHub -or $All) {
    Write-Host "Setting GitHub Secrets..." -ForegroundColor Yellow

    gh secret set AZURE_CLIENT_ID          --body $config.AzureClientId
    gh secret set AZURE_SUBSCRIPTION_ID    --body $config.SubscriptionId
    gh secret set AZURE_TENANT_ID          --body $config.TenantId
    gh secret set AZURE_RESOURCE_GROUP     --body $config.ResourceGroup
    gh secret set AZURE_LOCATION           --body $config.Location
    gh secret set APP_NAME                 --body $config.AppName
    gh secret set APP_SERVICE_PLAN_NAME    --body $config.AppServicePlanName

    Write-Host "GitHub Secrets set." -ForegroundColor Green
}

#---------------------------------------------------------------------------
# 2. Generate infra/main.local.bicepparam
#---------------------------------------------------------------------------
if ($Bicep -or $All) {
    Write-Host "Generating infra/main.local.bicepparam..." -ForegroundColor Yellow

    $content = @"
//
// main.local.bicepparam — generated by setup.ps1, do not commit
//
using './main.bicep'

param appName            = '$($config.AppName)'
param location           = '$($config.Location)'
param appServicePlanName = '$($config.AppServicePlanName)'
"@

    $outputPath = Join-Path $PSScriptRoot "infra/main.local.bicepparam"
    Set-Content -Path $outputPath -Value $content -Encoding UTF8

    Write-Host "infra/main.local.bicepparam generated." -ForegroundColor Green
}

Write-Host "Done." -ForegroundColor Green
